In [1]:
import pandas as pd

In [11]:
df = pd.read_csv('../liana_output_hsc/JMML_vs_Control_DEG_receptors.csv')

In [12]:
df.query('DEG_as_receptor=="ZEB1"')

Empty DataFrame
Columns: [source, target, ligand, DEG_as_receptor, lr_probs_jmml, lr_probs_control, delta_lr_probs, cellchat_pvals_jmml, cellchat_pvals_control, p_value, _merge]
Index: []

In [7]:
df.query('ligand=="ZEB1"')

Empty DataFrame
Columns: [source, target, ligand, DEG_as_receptor, lr_probs_jmml, lr_probs_control, delta_lr_probs, cellchat_pvals_jmml, cellchat_pvals_control, p_value, _merge]
Index: []

In [ ]:
df.query('ligand=="ZEB1"')

In [ ]:
import liana as li

resource = li.rs.select_resource("consensus")

print(resource[
    resource["ligand"].astype(str).str.contains("ZEB1", na=False)
    | resource["receptor"].astype(str).str.contains("ZEB1", na=False)
])